### ISSUE TITLE
Unvereinbarte Änderungen

### ISSUE THREAD

**Issue by Run-Derman** [ottenso/RunningDinner#32]
Wir haben uns in Teams aufgeteilt, Front- und Backend und in den Teams hat  jeder eine Aufgabe. Ich kümmere mich um die Datenbank. Wenn Änderungen am Datenbank vorgenommen werden müssen, sollte man mit mir absprechen bzw. eine Issue aufmachen und mir zuschreiben. So wie ich am Frontend nichts ändere, weil es mir nicht passt, sollte keiner auch am Datenbank was ändern, sie ihm nicht passt.
Deshalb ändere ich die Datenbank zurück wie wir am 30.10.2019 besprochen haben.

Vielen Dank für euer Verständnis.

**Comment by larslutz96** [comment]
Die Problematik wurde in der Gruppe besprochen und behoben.
